# Generated by Django 4.2 on 2023-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Input')),
                ('output', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Output')),
            ],
        ),
    ]
