# Generated by Django 4.2 on 2023-04-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imageproccess_input_alter_imageproccess_output'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProccess',
            new_name='ImageProcess',
        ),
    ]
