# Generated by Django 4.2 on 2023-04-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_imageprocess_input_alter_imageprocess_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprocess',
            name='output',
        ),
    ]
