# Generated by Django 4.2 on 2023-04-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_imageprocess_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocess',
            name='output',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Jpg'),
        ),
    ]
