# Generated by Django 4.2 on 2023-04-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_imageprocess_png'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprocess',
            old_name='png',
            new_name='filteer_png',
        ),
        migrations.RenameField(
            model_name='imageprocess',
            old_name='jpg',
            new_name='filter_jpg',
        ),
    ]
