# Generated by Django 4.2 on 2023-04-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_png_imageprocess_filteer_png_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprocess',
            old_name='filteer_png',
            new_name='filter_png',
        ),
    ]
