# Generated by Django 4.2 on 2023-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_imageprocess_filter_jpg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocess',
            name='sharp_jpg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sharpe Jpg'),
        ),
    ]
