# Generated by Django 4.2 on 2023-04-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_imageprocess_sharp_jpg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprocess',
            name='sharp_jpg',
        ),
    ]
