# Generated by Django 4.2 on 2023-04-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_imageprocess_sharp_jpg'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocess',
            name='sharpe_jpg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sharpe Jpg'),
        ),
    ]
