# Generated by Django 4.1.7 on 2023-04-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_imageprocess_filter_img_bg_remove_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprocess',
            name='filter_img_pdf',
        ),
    ]
