# Generated by Django 4.1.7 on 2023-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_imageprocess_filter_img_bg_remove_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocess',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Svg'),
        ),
    ]
