# Generated by Django 4.1.7 on 2023-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_imageprocess_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfToImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(blank=True, null=True, upload_to='', verbose_name='Input')),
                ('images_zip_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Images Zip File')),
            ],
        ),
    ]
