# Generated by Django 4.1.7 on 2023-04-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_pdftoimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdftoimage',
            name='images_zip_file',
        ),
    ]
