# Generated by Django 4.1.7 on 2023-04-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_pdftoimage_images_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftoimage',
            name='images_zip_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Images Zip File'),
        ),
    ]
