# Generated by Django 4.1.7 on 2023-04-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_pdftoimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocess',
            name='business_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imageprocess',
            name='email_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imageprocess',
            name='facebook_cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imageprocess',
            name='instagram_post',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imageprocess',
            name='instagram_story',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imageprocess',
            name='letterhead',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
