# Generated by Django 4.2 on 2023-05-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_imageprocess_business_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocess',
            name='eps',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
