# Generated by Django 4.2 on 2023-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_imageprocess_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocess',
            name='eps',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Eps'),
        ),
    ]
