# Generated by Django 4.2 on 2023-05-16 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_method', '0003_rename_charge_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Charge',
        ),
    ]
