# Generated by Django 4.2 on 2023-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0004_rename_payment_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='currency',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
