# Generated by Django 4.2 on 2023-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0006_charge_cvc_charge_exp_month_charge_exp_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='number',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='charge',
            name='client_secret',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='payment_id',
            field=models.TextField(null=True),
        ),
    ]
